---
kind: pipeline
type: docker
name: default

steps:
- name: install, build doc run scripts
  image: python:3.7
  commands:
  - git fetch --tags 
  - python setup.py install

- name: develop
  image: python:3.7
  commands:
  - python setup.py develop

- name: sdist
  image: python:3.7
  commands:
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: notify by email
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
